# Generated by Django 6.1.1 on 2026-10-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Booking Submitted'), ('HOD_APPROVED', 'HOD Approved'), ('HOD_REJECTED', 'HOD Rejected'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('COORDINATOR_REJECTED', 'Coordinator Rejected'), ('PRINCIPAL_APPROVED', 'Principal Approved (Confirmed)'), ('PRINCIPAL_REJECTED', 'Principal Rejected'), ('MODIFICATION_REQUESTED', 'Modification Requested'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='bookings.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval History',
                'verbose_name_plural': 'Approval Histories',
                'ordering': ['created_at'],
            },
        ),
    ]
