# Generated by Django 6.1.1 on 2026-10-02 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('responsible_person', models.CharField(blank=True, max_length=150)),
                ('responsible_contact', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('maintenance_reason', models.TextField(blank=True)),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('maintenance_end', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='halls/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seminar Hall',
                'verbose_name_plural': 'Seminar Halls',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HallFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='halls.hall')),
            ],
            options={
                'verbose_name': 'Hall Facility',
                'verbose_name_plural': 'Hall Facilities',
                'unique_together': {('hall', 'name')},
            },
        ),
    ]
