# Generated by Django 6.1.1 on 2026-10-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOOKING_CREATE', 'Booking Created'), ('BOOKING_UPDATE', 'Booking Updated'), ('BOOKING_SUBMIT', 'Booking Submitted'), ('BOOKING_APPROVE', 'Booking Approved'), ('BOOKING_REJECT', 'Booking Rejected'), ('BOOKING_CANCEL', 'Booking Cancelled'), ('HALL_CREATE', 'Hall Created'), ('HALL_UPDATE', 'Hall Updated'), ('HALL_MAINTENANCE', 'Hall Maintenance Status Changed'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('SETTINGS_UPDATE', 'System Settings Updated')], db_index=True, max_length=50)),
                ('booking_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('previous_value', models.TextField(blank=True)),
                ('updated_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
