# Generated by Django 6.1.1 on 2026-10-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('halls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Guest Lecture', 'Guest Lecture'), ('Faculty Development Programme', 'Faculty Development Programme (FDP)'), ('Meeting', 'Meeting'), ('Examination', 'Examination'), ('Cultural Event', 'Cultural Event'), ('Other', 'Other')], default='Seminar', max_length=50)),
                ('expected_participants', models.PositiveIntegerField(default=50)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('req_projector', models.BooleanField(default=False, verbose_name='Projector')),
                ('req_audio', models.BooleanField(default=False, verbose_name='Audio System')),
                ('req_microphone', models.BooleanField(default=False, verbose_name='Microphone')),
                ('req_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('req_video_conferencing', models.BooleanField(default=False, verbose_name='Video Conferencing')),
                ('req_ac', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('req_stage', models.BooleanField(default=False, verbose_name='Stage')),
                ('req_recording', models.BooleanField(default=False, verbose_name='Recording Facility')),
                ('chief_guest', models.CharField(blank=True, max_length=255)),
                ('event_description', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending HOD Approval'), ('HOD_APPROVED', 'Pending Coordinator Review'), ('COORDINATOR_APPROVED', 'Pending Principal Approval'), ('APPROVED', 'Approved / Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('current_approval_stage', models.CharField(choices=[('DRAFT', 'Draft'), ('HOD', 'HOD Verification'), ('COORDINATOR', 'Coordinator Verification'), ('PRINCIPAL', 'Principal Final Approval'), ('COMPLETED', 'Completed / Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_bookings', to='halls.hall')),
                ('alternative_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_bookings', to='halls.hall')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='departments.department')),
                ('preferred_hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferred_bookings', to='halls.hall')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-event_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='booking_docs/%Y/%m/')),
                ('title', models.CharField(max_length=150)),
                ('file_type', models.CharField(choices=[('schedule', 'Programme Schedule'), ('approval_doc', 'Approval Document'), ('other', 'Other Document')], default='schedule', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.booking')),
            ],
        ),
    ]
